version: '3.9'

services:
  database:
    ports:
      - "5432:5432"

  adminer:
    image: dockette/adminer:dg
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - internal

  mailer:
    image: axllent/mailpit:latest
    restart: unless-stopped
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - internal
    ports:
      - "1025:1025"
      - "8025:8025"
