version: '3.9'

services:
  database:
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:

volumes:
  db_data:

secrets:
  db_root_password:
    file: db_root_password.txt
