version: '3.9'

services:
  database:
    ports:
      - "5432:5432"

  adminer:
    image: dockette/adminer:dg
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - internal
